version: '3'
services: 
  web: 
    build:  
      context: .
      dockerfile: Dockerfile
    environment: 
      - DB_HOST=db
    ports: 
      - 3000:3000 
    depends_on: 
      - db 
  db: 
    image: postgres
    environment: 
      - POSTGRES_DB=test
